// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-LaVF2kXMblRjiJpABU8wExOYqqPgQn0',
    appId: '1:411334115364:ios:d4001b7af7fa3e1c9c58b1',
    messagingSenderId: '411334115364',
    projectId: 'budget-ai-cf437',
    storageBucket: 'budget-ai-cf437.firebasestorage.app',
    iosBundleId: 'com.example.budgetAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-LaVF2kXMblRjiJpABU8wExOYqqPgQn0',
    appId: '1:411334115364:ios:d4001b7af7fa3e1c9c58b1',
    messagingSenderId: '411334115364',
    projectId: 'budget-ai-cf437',
    storageBucket: 'budget-ai-cf437.firebasestorage.app',
    iosBundleId: 'com.example.budgetAi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBbH9HuKrlwChxs3W0ITDvbCq7PlsWUXM',
    appId: '1:411334115364:web:44d401818c0dea449c58b1',
    messagingSenderId: '411334115364',
    projectId: 'budget-ai-cf437',
    authDomain: 'budget-ai-cf437.firebaseapp.com',
    storageBucket: 'budget-ai-cf437.firebasestorage.app',
    measurementId: 'G-EZJSMF1ZB1',
  );

}